### ISSUE TITLE
VIM Key Error 

### ISSUE THREAD

**Issue by steamplayz** [colinhartigan/valorant-inventory-manager#20] opened 2022-02-11 13:44 UTC
When i launch the program it says 

 [ERROR] VIM_errors: error: please create an issue with the traceback below if this problem persists
 [ERROR] VIM_errors: Traceback (most recent call last):
  File "src\inventory_management\file_manager.py", line 42, in fetch_individual_inventory
KeyError: '4261af1e-0984-547e-8fcc-2095934ebbdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\inventory_management\skin_manager.py", line 102, in update_skin_database
  File "src\inventory_management\file_manager.py", line 44, in fetch_individual_inventory
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '4261af1e-0984-547e-8fcc-2095934ebbdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "src\server.py", line 73, in start
  File "src\inventory_management\skin_manager.py", line 104, in update_skin_database
  File "src\inventory_management\file_manager.py", line 65, in add_region
KeyError: '4261af1e-0984-547e-8fcc-2095934ebbdf'

**Comment by colinhartigan** [comment] 2022-02-11 15:23
duplicate of #7, fixing soon

**Closed by colinhartigan** 2022-02-11 15:23 UTC
Labels: duplicate
